# Generated by Django 5.2.4 on 2025-07-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='직원 이름')),
                ('department', models.CharField(max_length=100, verbose_name='소속 부서')),
                ('emp_id', models.CharField(max_length=20, unique=True, verbose_name='사번')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '직원 정보',
                'verbose_name_plural': '직원 정보',
                'db_table': 'emp_info',
            },
        ),
    ]
