# Generated by Django 5.2.4 on 2025-07-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_empinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, unique=True, verbose_name='부서명')),
                ('subject', models.CharField(max_length=200, verbose_name='이메일 제목')),
                ('content', models.TextField(verbose_name='이메일 내용')),
                ('auto_send', models.BooleanField(default=False, verbose_name='자동 발송')),
                ('require_approval', models.BooleanField(default=False, verbose_name='승인 필요')),
                ('cc_manager', models.BooleanField(default=False, verbose_name='매니저 참조')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '이메일 템플릿',
                'verbose_name_plural': '이메일 템플릿',
                'db_table': 'email_template',
            },
        ),
    ]
