# Generated by Django 5.2.4 on 2025-07-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, verbose_name='부서')),
                ('content', models.TextField(verbose_name='의뢰 내용')),
                ('submitted_by', models.CharField(max_length=100, verbose_name='상신자')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='상신 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '의뢰 상신',
                'verbose_name_plural': '의뢰 상신',
                'db_table': 'request_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
