# Generated by Django 5.2.4 on 2025-07-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_requestsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsubmission',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='의뢰 제목'),
        ),
    ]
