# Generated by Django 5.2.4 on 2025-07-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_requestsubmission_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(verbose_name='직원 ID')),
                ('employee_name', models.CharField(blank=True, max_length=100, verbose_name='직원명')),
                ('department', models.CharField(max_length=100, verbose_name='부서')),
                ('role', models.CharField(choices=[('결재', '결재'), ('병렬결재', '병렬결재'), ('합의', '합의'), ('통보', '통보')], max_length=10, verbose_name='결재 역할')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': '결재 역할',
                'verbose_name_plural': '결재 역할',
                'db_table': 'approval_roles',
                'unique_together': {('employee_id', 'department')},
            },
        ),
    ]
