# Generated by Django 5.2.4 on 2025-07-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_requestsubmission_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpApprovalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='직원 이름')),
                ('emp_id', models.CharField(max_length=20, verbose_name='사번')),
                ('role', models.CharField(choices=[('결재', '결재'), ('병렬결재', '병렬결재'), ('합의', '합의'), ('병렬합의', '병렬합의'), ('통보', '통보')], max_length=20, verbose_name='결재 역할')),
                ('department', models.CharField(max_length=100, verbose_name='부서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '직원 결재 역할',
                'verbose_name_plural': '직원 결재 역할',
                'db_table': 'emp_approval_role',
                'unique_together': {('emp_id', 'department')},
            },
        ),
    ]
