# Generated by Django 5.2.4 on 2025-07-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_empapprovalrole'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='empapprovalrole',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='empapprovalrole',
            name='emp_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='사번'),
        ),
        migrations.RemoveField(
            model_name='empapprovalrole',
            name='department',
        ),
    ]
