# Generated by Django 5.2.4 on 2025-07-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_approvalrole'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approvalrole',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='approvalrole',
            name='employee_id',
            field=models.IntegerField(unique=True, verbose_name='직원 ID'),
        ),
        migrations.RemoveField(
            model_name='approvalrole',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='approvalrole',
            name='department',
        ),
        migrations.RemoveField(
            model_name='approvalrole',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='approvalrole',
            name='updated_at',
        ),
    ]
