# Generated by Django 5.2.4 on 2025-08-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_empapprovalrole_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsubmission',
            name='assignee',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='담당자'),
        ),
        migrations.AddField(
            model_name='requestsubmission',
            name='change_request_items',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='변경의뢰 항목'),
        ),
        migrations.AddField(
            model_name='requestsubmission',
            name='eqpid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='EQPID'),
        ),
        migrations.AddField(
            model_name='requestsubmission',
            name='line_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Line ID'),
        ),
        migrations.AddField(
            model_name='requestsubmission',
            name='ppid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PPID'),
        ),
        migrations.AddField(
            model_name='requestsubmission',
            name='status',
            field=models.CharField(choices=[('대기중', '대기중'), ('진행중', '진행중'), ('완료', '완료'), ('보류', '보류')], default='대기중', max_length=20, verbose_name='상태'),
        ),
    ]
