# Generated by Django 5.2.4 on 2025-07-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_approvalrole_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrole',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='직원명'),
        ),
    ]
