# Generated by Django 4.2.23 on 2025-08-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_requestsubmission_assignee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='변경 아이템')),
                ('standard_TAT', models.IntegerField(help_text='표준 처리 시간(일 단위)', verbose_name='표준 TAT(일)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='코멘트')),
                ('reference', models.CharField(blank=True, max_length=200, null=True, verbose_name='참고사항')),
                ('phpsi_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='PHPSI 1')),
                ('phpsi_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='PHPSI 2')),
                ('phpsi_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='PHPSI 3')),
                ('phpsi_4', models.CharField(blank=True, max_length=100, null=True, verbose_name='PHPSI 4')),
                ('phpsi_5', models.CharField(blank=True, max_length=100, null=True, verbose_name='PHPSI 5')),
                ('phpsi_6', models.CharField(blank=True, max_length=100, null=True, verbose_name='PHPSI 6')),
                ('phpsi_7', models.CharField(blank=True, max_length=100, null=True, verbose_name='PHPSI 7')),
                ('phpsi_8', models.CharField(blank=True, max_length=100, null=True, verbose_name='PHPSI 8')),
                ('phpsi_9', models.CharField(blank=True, max_length=100, null=True, verbose_name='PHPSI 9')),
                ('phpsi_10', models.CharField(blank=True, max_length=100, null=True, verbose_name='PHPSI 10')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '가이드 DB',
                'verbose_name_plural': '가이드 DB',
                'db_table': 'guide_db',
                'ordering': ['item'],
            },
        ),
    ]
