# Generated by Django 5.2.4 on 2025-09-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_employee_employee_number_requestsubmission_excel_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestsubmission",
            name="max_tat",
            field=models.IntegerField(
                blank=True,
                help_text="선택된 변경 항목 중 가장 긴 표준 TAT",
                null=True,
                verbose_name="Max TAT",
            ),
        ),
    ]
