# Generated by Django 5.2.4 on 2025-09-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_guidedb"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestsubmission",
            name="excel_1",
            field=models.TextField(
                blank=True, null=True, verbose_name="엑셀 표1 (HTML)"
            ),
        ),
        migrations.AddField(
            model_name="requestsubmission",
            name="excel_2",
            field=models.TextField(
                blank=True, null=True, verbose_name="엑셀 표2 (HTML)"
            ),
        ),
        migrations.AddField(
            model_name="requestsubmission",
            name="max_tat",
            field=models.IntegerField(
                blank=True,
                help_text="선택된 변경 항목 중 가장 긴 표준 TAT",
                null=True,
                verbose_name="Max TAT",
            ),
        ),
    ]
